#!/usr/bin/env bash
# A Bash script that displays the phrase “Best School” exactly 10 times using the while loop.

counter=10

while (( counter > 0 )); do
    echo "Best School"
    (( counter-- ))
done
