#!/usr/bin/env bash
# A Bash script that displays the phrase “Best School” exactly 10 times using the util loop.

counter=1

until (( counter > 10 )); do
    echo "Best School"
    (( counter++ ))
done
