#!/usr/bin/env bash
# Write a Bash script that displays “Best School” 10 times. However, for the 9th iteration, your script should display “Best School” and then, on a new line, display “Hi”.

counter=10

while (( counter > 0 )); do
    echo "Best School"
    if [ $counter -eq 2 ]; then
        echo "Hi"
    fi
    (( counter-- ))
done
