#!/usr/bin/env bash
# Display numbers from 1 to 20 with “bad luck” messages

counter=1
while (( counter <= 20 )); do
    case $counter in
        4)
            echo "$counter"
            echo "bad luck from China"
            ;;
        9)
            echo "$counter"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$counter"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac
    (( counter++ ))
done
